CREATE TABLE ParentTask (
  Parent_ID INT AUTO_INCREMENT PRIMARY KEY,
  Parent_Task VARCHAR(50) NOT NULL
);

CREATE TABLE Task (
  Task_ID INT AUTO_INCREMENT PRIMARY KEY,
  Parent_ID INT NULL,
  Task VARCHAR(50) NOT NULL,
  Start_Date DATETIME NOT NULL,
  End_Date DATETIME NULL,
  Priority INT NOT NULL,
  Status VARCHAR(20),
  FOREIGN KEY (Parent_ID) REFERENCES Task (Task_ID),
  );
